server:
  port: 8084

spring:
  application:
      name: UserService
  data:
   mongodb:
     uri: mongodb+srv://Mitesh:tZWcMFA9xyQ8pNbh@clustertest.mbl85.mongodb.net/AWSCertificationPortalUpdatedDB?retryWrites=true&w=majority
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher   
data:
  exception:
     dataExists: User Already Exists..!!
     dataNotFound: User Id Not Found..!!
     emailExists: Email Already Exists..!!

eureka:
   client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8761/eureka/
    
logging:
  file:
    name: UserService.log
    
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000 # 1hr duration by default: 60 minutes * 60 seconds * 1000 miliseconds



