server:
    port: 8080
eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/

spring:
 application:
  name: APIGatewayService
 cloud:
    gateway:
     globalcors:
       cors-configurations:
          '[/**]' :
            allowedOrigins : "http://localhost:3000"
            allowCredentials: true
            allowedHeaders : "*"
            allowedMethods : 
             - GET
             - POST
             - PUT
             - DELETE
    
     routes:
      - id: CertificationDetailService
        uri: http://localhost:8082/
        predicates:
        - Path=/api/certification/**
      - id: BatchDetailService
        uri: http://localhost:8083/
        predicates:
        - Path=/api/batch/**
      - id: AdminService
        uri: http://localhost:8085/
        predicates:
        - Path=/api/admin/**
      - id: UserService
        uri: http://localhost:8084/
        predicates:
        - Path=/api/user/**




